dataloader_cfg:
  batch_size: 2
  black_level: 512
  crop_size: 512
  eval_csv_path: dataset/Sony_val_list.txt
  num_workers: 0
  pin_memory: true
  root_dir: /home/dsteam/Desktop
  shuffle: true
  stack_bayer: true
  subset: 1
  train_csv_path: dataset/Sony_train_list.txt
handlers_cfg:
  dirname: sid_vanilla
  filename_prefix: sid_vanilla
  multi_gpu: true
  n_saved: 10
  patience: 100
  resume: true
  save_interval: 1
  score_function_name: L1
  score_is_loss: true
train_cfg:
  gamma: 0.1
  half_precision: true
  initial_lr: 1e-4
  loss_fn: L1
  max_epochs: 4000
  model: cfg/model_cfg/dropout_u_net.cfg
  momentum: 0.9
  optimizer_type: Adam
  scheduler_type: steps
  step_size: 2000
  weight_decay: 0.1
